### ISSUE TITLE
[ic-top-navigation] - inconsistent rendering of search icon at small screen sizes in high contrast mode

### ISSUE THREAD

**Issue by MI6-286** [mi6/ic-ui-kit#2369]
## Summary of the bug 
The search icon sometimes renders in dark grey in high contrast mode at small screen sizes, meaning the button appears empty.

## 🪜 How to reproduce 
1. Either run the Cypress test It("should render with navigation items in high contrast mode") within IcTopNavigation.cy.tsx and view the image generated
2. Or view the 'With search' story within React Storybook with high contrast mode emulation - ensure screen size is small enough to switch from search bar to search icon

## 📸 Screenshots or code 
Incorrect (dark grey magnifying glass):
![image](https://github.com/user-attachments/assets/f774918f-8c27-4fdf-9b42-09d165b87f46)

Correct (white magnifying glass):
![image](https://github.com/user-attachments/assets/bda8e75d-7f20-4f28-a267-0b54c5cd1f51)

## 🧐 Expected behaviour 
The search icon should consistently be displayed.

## Additional info 
The issue mostly occurs when running the Cypress visual regression test, both locally and on the CI. However, I have been able to recreate the issue in Storybook when decreasing screen size while in high contrast mode. I haven't been able to recreate the issue in Stackblitz.

**Comment by GCHQ-Developer-299** [comment]
This might have been fixed by recent changes to components-within-components in Dark mode (https://github.com/mi6/ic-ui-kit/pull/2929) be sure to check

**Comment by MI6-286** [comment]
Checked following #2929 but issue still seen when running relevant Cypress test.

**Comment by BluePandaCard** [comment]
This has been completed so can be moved to Done 🙂
